// Generated by Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)
#ifndef ZIGGEOMEDIASWIFTSDK_SWIFT_H
#define ZIGGEOMEDIASWIFTSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AVFAudio;
@import AVFoundation;
@import CoreGraphics;
@import CoreMedia;
@import Foundation;
@import MessageUI;
@import ObjectiveC;
@import QuartzCore;
@import ReplayKit;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ZiggeoMediaSwiftSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif



SWIFT_CLASS("_TtC19ZiggeoMediaSwiftSDK9AudioData")
@interface AudioData : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIProgressView;
@class NSLayoutConstraint;
@class NSCoder;
@class NSNumber;

SWIFT_CLASS("_TtC19ZiggeoMediaSwiftSDK14AudioLevelView")
@interface AudioLevelView : UIView
@property (nonatomic, strong) IBOutlet UIView * _Null_unspecified contentView;
@property (nonatomic, weak) IBOutlet UIProgressView * _Null_unspecified progressBar;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified widthConstraint;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic) IBInspectable double currentLevel;
@end


SWIFT_CLASS("_TtC19ZiggeoMediaSwiftSDK18AudioPlayerManager")
@interface AudioPlayerManager : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class AVAudioPlayer;

@interface AudioPlayerManager (SWIFT_EXTENSION(ZiggeoMediaSwiftSDK)) <AVAudioPlayerDelegate>
- (void)audioPlayerDidFinishPlaying:(AVAudioPlayer * _Nonnull)player successfully:(BOOL)flag;
@end


SWIFT_CLASS("_TtC19ZiggeoMediaSwiftSDK20AudioRecorderManager")
@interface AudioRecorderManager : NSObject
- (void)timerDidUpdateMeter;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class AVAudioRecorder;

@interface AudioRecorderManager (SWIFT_EXTENSION(ZiggeoMediaSwiftSDK)) <AVAudioRecorderDelegate>
- (void)audioRecorderDidFinishRecording:(AVAudioRecorder * _Nonnull)recorder successfully:(BOOL)flag;
- (void)audioRecorderEncodeErrorDidOccur:(AVAudioRecorder * _Nonnull)recorder error:(NSError * _Nullable)error;
@end


SWIFT_CLASS("_TtC19ZiggeoMediaSwiftSDK15AudioStreamData")
@interface AudioStreamData : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// <ul>
///   <li>
///     Subclass this class to use
///   </li>
///   <li>
///     @note
///   </li>
///   <li>
///     Instructions:
///   </li>
///   <li>
///     <ul>
///       <li>
///         Subclass this class
///       </li>
///     </ul>
///   </li>
///   <li>
///     <ul>
///       <li>
///         Associate it with a nib via File’s Owner (Whose name is defined by [-nibName])
///       </li>
///     </ul>
///   </li>
///   <li>
///     <ul>
///       <li>
///         Bind contentView to the root view of the nib
///       </li>
///     </ul>
///   </li>
///   <li>
///     <ul>
///       <li>
///         Then you can insert it either in code or in a xib/storyboard, your choice
///       </li>
///     </ul>
///   </li>
/// </ul>
SWIFT_CLASS("_TtC19ZiggeoMediaSwiftSDK11BaseNibView")
@interface BaseNibView : UIView
@property (nonatomic, strong) IBOutlet UIView * _Null_unspecified contentView;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
@end

enum AudioVisualizationMode : NSInteger;
@class UIColor;
@class NSURL;

SWIFT_CLASS("_TtC19ZiggeoMediaSwiftSDK22AudioVisualizationView")
@interface AudioVisualizationView : BaseNibView
@property (nonatomic) IBInspectable CGFloat meteringLevelBarWidth;
@property (nonatomic) IBInspectable CGFloat meteringLevelBarInterItem;
@property (nonatomic) IBInspectable CGFloat meteringLevelBarCornerRadius;
@property (nonatomic) IBInspectable BOOL meteringLevelBarSingleStick;
@property (nonatomic) enum AudioVisualizationMode audioVisualizationMode;
@property (nonatomic, copy) NSArray<NSNumber *> * _Nullable meteringLevels;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull gradientStartColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull gradientEndColor;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)drawRect:(CGRect)rect;
- (void)reset;
- (void)addWithMeteringLevel:(float)meteringLevel;
- (NSArray<NSNumber *> * _Nonnull)scaleSoundDataToFitScreen SWIFT_WARN_UNUSED_RESULT;
- (void)playFrom:(NSURL * _Nonnull)url;
- (void)playFor:(NSTimeInterval)duration;
- (void)pause;
- (void)stop;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

typedef SWIFT_ENUM(NSInteger, AudioVisualizationMode, closed) {
  AudioVisualizationModeRead = 0,
  AudioVisualizationModeWrite = 1,
};



SWIFT_CLASS("_TtC19ZiggeoMediaSwiftSDK18CapturePreviewView")
@interface CapturePreviewView : UIView
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) Class _Nonnull layerClass;)
+ (Class _Nonnull)layerClass SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19ZiggeoMediaSwiftSDK11Chronometer")
@interface Chronometer : NSObject
- (nonnull instancetype)initWithTimeInterval:(NSTimeInterval)timeInterval OBJC_DESIGNATED_INITIALIZER;
- (void)startWithShouldFire:(BOOL)fire;
- (void)pause;
- (void)stop;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC19ZiggeoMediaSwiftSDK12ContentModel")
@interface ContentModel : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UITableView;
@class NSIndexPath;
@class UITableViewCell;
@class NSString;
@class NSBundle;

SWIFT_CLASS("_TtC19ZiggeoMediaSwiftSDK13CoverSelector")
@interface CoverSelector : UIViewController <UITableViewDataSource, UITableViewDelegate>
@property (nonatomic, weak) IBOutlet UITableView * _Null_unspecified tableView;
- (void)viewDidLoad;
- (IBAction)useDefaultCover:(id _Nonnull)sender;
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

@class UIImageView;

SWIFT_CLASS("_TtC19ZiggeoMediaSwiftSDK22CoverSelectorTableCell")
@interface CoverSelectorTableCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified coverView;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19ZiggeoMediaSwiftSDK14DeviceInfoData")
@interface DeviceInfoData : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19ZiggeoMediaSwiftSDK4Face")
@interface Face : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19ZiggeoMediaSwiftSDK15FaceOutlineView")
@interface FaceOutlineView : UIView
- (void)drawRect:(CGRect)rect;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19ZiggeoMediaSwiftSDK12FileInfoData")
@interface FileInfoData : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC19ZiggeoMediaSwiftSDK9ImageData")
@interface ImageData : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19ZiggeoMediaSwiftSDK15ImageStreamData")
@interface ImageStreamData : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19ZiggeoMediaSwiftSDK12LuxMeterView")
@interface LuxMeterView : UIView
@property (nonatomic, strong) IBOutlet UIView * _Null_unspecified contentView;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imageView;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic) IBInspectable double currentLuminousity;
@end



@class CALayer;
@class UITouch;
@class UIEvent;

IB_DESIGNABLE
SWIFT_CLASS("_TtC19ZiggeoMediaSwiftSDK11RangeSlider")
@interface RangeSlider : UIControl
@property (nonatomic) IBInspectable BOOL lowerLayerSelected;
@property (nonatomic) IBInspectable double minimumValue;
@property (nonatomic) IBInspectable double maximumValue;
@property (nonatomic) IBInspectable double lowerValue;
@property (nonatomic) IBInspectable double upperValue;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull trackTintColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull trackHighlightTintColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull thumbTintColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull thumbBorderColor;
@property (nonatomic) IBInspectable CGFloat thumbBorderWidth;
@property (nonatomic) IBInspectable CGFloat curvaceousness;
@property (nonatomic) CGRect frame;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSublayersOfLayer:(CALayer * _Nonnull)of;
- (BOOL)beginTrackingWithTouch:(UITouch * _Nonnull)touch withEvent:(UIEvent * _Nullable)event SWIFT_WARN_UNUSED_RESULT;
- (BOOL)continueTrackingWithTouch:(UITouch * _Nonnull)touch withEvent:(UIEvent * _Nullable)event SWIFT_WARN_UNUSED_RESULT;
- (void)endTrackingWithTouch:(UITouch * _Nullable)touch withEvent:(UIEvent * _Nullable)event;
@end


SWIFT_CLASS("_TtC19ZiggeoMediaSwiftSDK21RangeSliderThumbLayer")
@interface RangeSliderThumbLayer : CALayer
- (void)drawInContext:(CGContextRef _Nonnull)ctx;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithLayer:(id _Nonnull)layer OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19ZiggeoMediaSwiftSDK21RangeSliderTrackLayer")
@interface RangeSliderTrackLayer : CALayer
- (void)drawInContext:(CGContextRef _Nonnull)ctx;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithLayer:(id _Nonnull)layer OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19ZiggeoMediaSwiftSDK18ScalableConstraint")
@interface ScalableConstraint : NSLayoutConstraint
@property (nonatomic) IBInspectable CGFloat scale;
@property (nonatomic) IBInspectable CGFloat basicConstant;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSNotification;

SWIFT_CLASS("_TtC19ZiggeoMediaSwiftSDK14TPGAudioPlayer")
@interface TPGAudioPlayer : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)playingStalled:(NSNotification * _Nonnull)notification;
- (void)playerDidReachEnd:(NSNotification * _Nonnull)notification;
- (void)playerItemTimeJumpedNotification:(NSNotification * _Nonnull)notification;
@end




SWIFT_CLASS("_TtC19ZiggeoMediaSwiftSDK9VideoData")
@interface VideoData : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19ZiggeoMediaSwiftSDK15VideoStreamData")
@interface VideoStreamData : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19ZiggeoMediaSwiftSDK9ViewModel")
@interface ViewModel : NSObject
@property (nonatomic, copy) NSURL * _Nullable audioFilePathLocal;
@property (nonatomic, copy) NSArray<NSNumber *> * _Nullable meteringLevels;
@property (nonatomic, copy) void (^ _Nullable audioMeteringLevelUpdate)(float);
@property (nonatomic, copy) void (^ _Nullable audioDidFinish)(void);
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)askAudioRecordingPermissionWithCompletion:(void (^ _Nullable)(BOOL))completion;
- (void)startRecordingWithCompletion:(void (^ _Nonnull)(NSURL * _Nullable, NSArray<NSNumber *> * _Nullable, NSError * _Nullable))completion;
- (BOOL)stopRecordingAndReturnError:(NSError * _Nullable * _Nullable)error;
- (BOOL)resetRecordingAndReturnError:(NSError * _Nullable * _Nullable)error;
- (double)startPlaying SWIFT_WARN_UNUSED_RESULT;
- (void)setCurrentTime:(NSTimeInterval)currentTime;
- (BOOL)pausePlayingAndReturnError:(NSError * _Nullable * _Nullable)error;
@end


SWIFT_CLASS("_TtC19ZiggeoMediaSwiftSDK6Ziggeo")
@interface Ziggeo : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class MFMailComposeViewController;

@interface Ziggeo (SWIFT_EXTENSION(ZiggeoMediaSwiftSDK)) <MFMailComposeViewControllerDelegate>
- (void)mailComposeController:(MFMailComposeViewController * _Nonnull)controller didFinishWithResult:(MFMailComposeResult)result error:(NSError * _Nullable)error;
@end

@class UIImagePickerController;

@interface Ziggeo (SWIFT_EXTENSION(ZiggeoMediaSwiftSDK)) <UIImagePickerControllerDelegate, UINavigationControllerDelegate>
- (void)imagePickerController:(UIImagePickerController * _Nonnull)picker didFinishPickingMediaWithInfo:(NSDictionary<UIImagePickerControllerInfoKey, id> * _Nonnull)info;
- (void)imagePickerControllerDidCancel:(UIImagePickerController * _Nonnull)picker;
@end

@class UILabel;
@class UISlider;
@class UIActivityIndicatorView;

SWIFT_CLASS("_TtC19ZiggeoMediaSwiftSDK17ZiggeoAudioPlayer")
@interface ZiggeoAudioPlayer : UIViewController
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified statusLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified currentTimeLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified totalTimeLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified durationLabel;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified playImageView;
@property (nonatomic, weak) IBOutlet UISlider * _Null_unspecified timeSlider;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified beforeButtonView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified rewindButtonView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified playButtonView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified forwardButtonView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified nextButtonView;
@property (nonatomic, weak) IBOutlet UIActivityIndicatorView * _Null_unspecified loadingIndicator;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)viewDidLoad;
- (IBAction)onChangeCurrentTime:(UISlider * _Nonnull)sender;
- (IBAction)onPlayOrPause:(id _Nonnull)sender;
- (IBAction)onClose:(id _Nonnull)sender;
- (IBAction)onPlayBeforeItem:(id _Nonnull)sender;
- (IBAction)onPlayRewind:(id _Nonnull)sender;
- (IBAction)onPlayForward:(id _Nonnull)sender;
- (IBAction)onPlayNextItem:(id _Nonnull)sender;
- (void)sliderTimerTriggered;
- (void)episodeLoadedNotification:(NSNotification * _Nonnull)notification;
- (void)playerDidReachEndNotification:(NSNotification * _Nonnull)notification;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC19ZiggeoMediaSwiftSDK19ZiggeoAudioRecorder")
@interface ZiggeoAudioRecorder : UIViewController
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified statusLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified timeLabel;
@property (nonatomic, weak) IBOutlet AudioVisualizationView * _Null_unspecified audioVisualizationView;
@property (nonatomic, weak) IBOutlet UISlider * _Null_unspecified timeSlider;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified durationLabel;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified reloadImageView;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified recordImageView;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified uploadImageView;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (IBAction)onClose:(id _Nonnull)sender;
- (IBAction)onRerecord:(id _Nonnull)sender;
- (IBAction)onRecord:(id _Nonnull)sender;
- (IBAction)onUpload:(id _Nonnull)sender;
- (IBAction)timeChanged:(UISlider * _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC19ZiggeoMediaSwiftSDK12ZiggeoAudios")
@interface ZiggeoAudios : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC19ZiggeoMediaSwiftSDK18ZiggeoCacheManager")
@interface ZiggeoCacheManager : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC19ZiggeoMediaSwiftSDK12ZiggeoConfig")
@interface ZiggeoConfig : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSURLSession;
@class NSURLSessionDataTask;
@class NSData;
@class NSURLSessionTask;

SWIFT_CLASS("_TtC19ZiggeoMediaSwiftSDK13ZiggeoConnect")
@interface ZiggeoConnect : NSObject <NSURLSessionDataDelegate>
- (void)URLSession:(NSURLSession * _Nonnull)session dataTask:(NSURLSessionDataTask * _Nonnull)dataTask didReceiveData:(NSData * _Nonnull)data;
- (void)URLSession:(NSURLSession * _Nonnull)session task:(NSURLSessionTask * _Nonnull)task didCompleteWithError:(NSError * _Nullable)error;
- (void)URLSession:(NSURLSession * _Nonnull)session task:(NSURLSessionTask * _Nonnull)task didSendBodyData:(int64_t)bytesSent totalBytesSent:(int64_t)totalBytesSent totalBytesExpectedToSend:(int64_t)totalBytesExpectedToSend;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSURLResponse;

SWIFT_PROTOCOL("_TtP19ZiggeoMediaSwiftSDK14ZiggeoDelegate_")
@protocol ZiggeoDelegate
@optional
- (void)ziggeoRecorderLuxMeter:(double)luminousity;
- (void)ziggeoRecorderAudioMeter:(double)audioLevel;
- (void)ziggeoRecorderFaceDetected:(NSInteger)faceID rect:(CGRect)rect;
- (void)ziggeoRecorderReady;
- (void)ziggeoRecorderCanceled;
- (void)ziggeoRecorderStarted;
- (void)ziggeoRecorderStopped:(NSString * _Nonnull)path;
- (void)ziggeoRecorderCurrentRecordedDurationSeconds:(double)seconds;
- (void)ziggeoRecorderPlaying;
- (void)ziggeoRecorderPaused;
- (void)ziggeoRecorderRerecord;
- (void)ziggeoRecorderManuallySubmitted;
- (void)ziggeoStreamingStarted;
- (void)ziggeoStreamingStopped;
- (void)preparingToUpload:(NSString * _Nonnull)path;
- (void)failedToUpload:(NSString * _Nonnull)path;
- (void)uploadStarted:(NSString * _Nonnull)path token:(NSString * _Nonnull)token streamToken:(NSString * _Nonnull)streamToken backgroundTask:(NSURLSessionTask * _Nonnull)backgroundTask;
- (void)uploadProgress:(NSString * _Nonnull)path token:(NSString * _Nonnull)token streamToken:(NSString * _Nonnull)streamToken totalBytesSent:(int64_t)totalBytesSent totalBytesExpectedToSend:(int64_t)totalBytesExpectedToSend;
- (void)uploadFinished:(NSString * _Nonnull)path token:(NSString * _Nonnull)token streamToken:(NSString * _Nonnull)streamToken;
- (void)uploadVerified:(NSString * _Nonnull)path token:(NSString * _Nonnull)token streamToken:(NSString * _Nonnull)streamToken response:(NSURLResponse * _Nullable)response error:(NSError * _Nullable)error json:(NSDictionary * _Nullable)json;
- (void)uploadProcessing:(NSString * _Nonnull)path token:(NSString * _Nonnull)token streamToken:(NSString * _Nonnull)streamToken;
- (void)uploadProcessed:(NSString * _Nonnull)path token:(NSString * _Nonnull)token streamToken:(NSString * _Nonnull)streamToken;
- (void)delete:(NSString * _Nonnull)token streamToken:(NSString * _Nonnull)streamToken response:(NSURLResponse * _Nullable)response error:(NSError * _Nullable)error json:(NSDictionary * _Nullable)json;
- (void)checkCameraPermission:(BOOL)granted;
- (void)checkMicrophonePermission:(BOOL)granted;
- (void)checkPhotoLibraryPermission:(BOOL)granted;
- (void)checkHasCamera:(BOOL)hasCamera;
- (void)checkHasMicrophone:(BOOL)hasMicrophone;
- (void)ziggeoPlayerPlaying;
- (void)ziggeoPlayerPaused;
- (void)ziggeoPlayerEnded;
- (void)ziggeoPlayerSeek:(double)positionMillis;
- (void)ziggeoPlayerReadyToPlay;
@end


SWIFT_CLASS("_TtC19ZiggeoMediaSwiftSDK12ZiggeoImages")
@interface ZiggeoImages : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class AVPlayerItem;

SWIFT_CLASS("_TtC19ZiggeoMediaSwiftSDK12ZiggeoPlayer")
@interface ZiggeoPlayer : AVQueuePlayer
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithURL:(NSURL * _Nonnull)url OBJC_DESIGNATED_INITIALIZER;
- (void)contentDidFinishPlaying:(NSNotification * _Nonnull)notification;
- (void)observeValueForKeyPath:(NSString * _Nullable)keyPath ofObject:(id _Nullable)object change:(NSDictionary<NSKeyValueChangeKey, id> * _Nullable)change context:(void * _Nullable)context;
- (nonnull instancetype)initWithItems:(NSArray<AVPlayerItem *> * _Nonnull)items SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithPlayerItem:(AVPlayerItem * _Nullable)item SWIFT_UNAVAILABLE;
@end


SWIFT_PROTOCOL("_TtP19ZiggeoMediaSwiftSDK26ZiggeoQRCodeReaderDelegate_")
@protocol ZiggeoQRCodeReaderDelegate
- (void)ziggeoQRCodeScaned:(NSString * _Nonnull)qrCode;
@end


SWIFT_CLASS("_TtC19ZiggeoMediaSwiftSDK32ZiggeoQRCodeReaderViewController")
@interface ZiggeoQRCodeReaderViewController : UIViewController
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified preview;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (IBAction)onBack:(id _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

@class AVCaptureMetadataOutput;
@class AVMetadataObject;
@class AVCaptureConnection;

@interface ZiggeoQRCodeReaderViewController (SWIFT_EXTENSION(ZiggeoMediaSwiftSDK)) <AVCaptureMetadataOutputObjectsDelegate>
- (void)captureOutput:(AVCaptureMetadataOutput * _Nonnull)output didOutputMetadataObjects:(NSArray<AVMetadataObject *> * _Nonnull)metadataObjects fromConnection:(AVCaptureConnection * _Nonnull)connection;
@end

@class UIButton;

SWIFT_CLASS("_TtC19ZiggeoMediaSwiftSDK26ZiggeoRecordedVideoPreview")
@interface ZiggeoRecordedVideoPreview : UIViewController
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified playPauseButton;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified videoPlaceholder;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) BOOL shouldAutorotate;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (void)itemDidFinishPlaying:(NSNotification * _Nonnull)notification;
- (void)viewDidAppear:(BOOL)animated;
- (IBAction)retake:(id _Nonnull)sender;
- (IBAction)play:(id _Nonnull)sender;
- (IBAction)upload:(id _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

@protocol UIViewControllerTransitionCoordinator;
@class UIGestureRecognizer;

SWIFT_CLASS("_TtC19ZiggeoMediaSwiftSDK14ZiggeoRecorder")
@interface ZiggeoRecorder : UIViewController
@property (nonatomic, weak) IBOutlet CapturePreviewView * _Null_unspecified previewView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified cameraUnavailableLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified recordingDurationLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified startDelayLabel;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified recordButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified cameraButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified closeButton;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified controlsView;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified blurringPreviewView;
@property (nonatomic, weak) IBOutlet LuxMeterView * _Null_unspecified luxMeterView;
@property (nonatomic, weak) IBOutlet AudioLevelView * _Null_unspecified audioLevelView;
@property (nonatomic, weak) IBOutlet FaceOutlineView * _Null_unspecified faceOutlineView;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
@property (nonatomic, readonly) BOOL shouldAutorotate;
@property (nonatomic, readonly) UIInterfaceOrientationMask supportedInterfaceOrientations;
- (void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id <UIViewControllerTransitionCoordinator> _Nonnull)coordinator;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (void)observeValueForKeyPath:(NSString * _Nullable)keyPath ofObject:(id _Nullable)object change:(NSDictionary<NSKeyValueChangeKey, id> * _Nullable)change context:(void * _Nullable)context;
- (void)viewDidLoad;
- (IBAction)onCloseButtonTap:(id _Nonnull)sender;
- (IBAction)changeCamera:(id _Nonnull)sender;
- (IBAction)focusAndExposeTap:(UIGestureRecognizer * _Nonnull)gestureRecognizer;
- (IBAction)toggleMovieRecording:(id _Nonnull)sender;
- (void)updateStartDelay;
- (void)updateDuration;
- (void)subjectAreaDidChange:(NSNotification * _Nonnull)notification;
- (void)sessionRuntimeError:(NSNotification * _Nonnull)notification;
- (void)sessionWasInterrupted:(NSNotification * _Nonnull)notification;
- (void)sessionInterruptionEnded:(NSNotification * _Nonnull)notification;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


@interface ZiggeoRecorder (SWIFT_EXTENSION(ZiggeoMediaSwiftSDK)) <AVCaptureMetadataOutputObjectsDelegate>
- (void)captureOutput:(AVCaptureMetadataOutput * _Nonnull)output didOutputMetadataObjects:(NSArray<AVMetadataObject *> * _Nonnull)metadataObjects fromConnection:(AVCaptureConnection * _Nonnull)connection;
@end

@class AVCaptureOutput;

@interface ZiggeoRecorder (SWIFT_EXTENSION(ZiggeoMediaSwiftSDK)) <AVCaptureAudioDataOutputSampleBufferDelegate, AVCaptureVideoDataOutputSampleBufferDelegate>
- (void)captureOutput:(AVCaptureOutput * _Nonnull)output didOutputSampleBuffer:(CMSampleBufferRef _Nonnull)sampleBuffer fromConnection:(AVCaptureConnection * _Nonnull)connection;
@end



SWIFT_CLASS("_TtC19ZiggeoMediaSwiftSDK33ZiggeoScreenRecorderSampleHandler")
@interface ZiggeoScreenRecorderSampleHandler : RPBroadcastSampleHandler
- (void)broadcastStartedWithSetupInfo:(NSDictionary<NSString *, NSObject *> * _Nullable)setupInfo;
- (void)broadcastPaused;
- (void)broadcastResumed;
- (void)processSampleBuffer:(CMSampleBufferRef _Nonnull)sampleBuffer withType:(RPSampleBufferType)sampleBufferType;
- (void)broadcastFinished;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19ZiggeoMediaSwiftSDK22ZiggeoUploadingHandler")
@interface ZiggeoUploadingHandler : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UITapGestureRecognizer;

SWIFT_CLASS("_TtC19ZiggeoMediaSwiftSDK17ZiggeoVideoEditor")
@interface ZiggeoVideoEditor : UIViewController
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified videoLayer;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified cropButton;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified frameContainerView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified imageFrameView;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (IBAction)cropVideo:(id _Nonnull)sender;
- (IBAction)onClose:(id _Nonnull)sender;
- (void)tapOnVideoLayerWithTap:(UITapGestureRecognizer * _Nonnull)tap;
- (void)rangeSliderValueChanged:(RangeSlider * _Nonnull)rangeSlider;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC19ZiggeoMediaSwiftSDK18ZiggeoVideoLibrary")
@interface ZiggeoVideoLibrary : UIImagePickerController
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidAppear:(BOOL)animated;
- (nonnull instancetype)initWithNavigationBarClass:(Class _Nullable)navigationBarClass toolbarClass:(Class _Nullable)toolbarClass SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithRootViewController:(UIViewController * _Nonnull)rootViewController SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

@class UINavigationController;

@interface ZiggeoVideoLibrary (SWIFT_EXTENSION(ZiggeoMediaSwiftSDK)) <UIImagePickerControllerDelegate, UINavigationControllerDelegate>
- (void)imagePickerController:(UIImagePickerController * _Nonnull)picker didFinishPickingMediaWithInfo:(NSDictionary<UIImagePickerControllerInfoKey, id> * _Nonnull)info;
- (void)imagePickerControllerDidCancel:(UIImagePickerController * _Nonnull)picker;
- (void)navigationController:(UINavigationController * _Nonnull)navigationController didShowViewController:(UIViewController * _Nonnull)viewController animated:(BOOL)animated;
@end


SWIFT_CLASS("_TtC19ZiggeoMediaSwiftSDK12ZiggeoVideos")
@interface ZiggeoVideos : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif
