# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'TestApplication' do

  # Pods for TestApplication
   pod 'ZiggeoMediaSwiftSDK', :git => 'https://github.com/Ziggeo/Swift-Client-SDK.git'

end
