# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'TestApplication' do

  # Pods for TestApplication
  pod 'ZiggeoSwift', :git => 'https://github.com/Ziggeo/Swift-Client-SDK.git'
#  pod 'ZiggeoSwift', :path => '../../'

end
