# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TestApplication' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestApplication

  pod 'GoogleAds-IMA-iOS-SDK', '3.11.3'
#  pod 'ZiggeoSwiftSDK', :path => '../..'
  pod 'ZiggeoSwiftSDK', :git => 'https://github.com/Ziggeo/Swift-Client-SDK.git'

end
