# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'TestApplication' do

  # Pods for TestApplication
  pod 'ZiggeoSwiftSDK', :git => 'https://github.com/Ziggeo/Swift-Client-SDK.git', :branch => 'no-blurring'

end
