// Generated by Apple Swift version 3.0.2 (swiftlang-800.0.63 clang-800.0.42.1)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if defined(__has_attribute) && __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if defined(__has_feature) && __has_feature(modules)
@import UIKit;
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import AVFoundation;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class NSCoder;

SWIFT_CLASS("_TtC20ZiggeoSwiftFramework18CapturePreviewView")
@interface CapturePreviewView : UIView
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) Class _Nonnull layerClass;)
+ (Class _Nonnull)layerClass;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UITableView;
@class UITableViewCell;
@class NSBundle;

SWIFT_CLASS("_TtC20ZiggeoSwiftFramework13CoverSelector")
@interface CoverSelector : UIViewController <UIScrollViewDelegate, UITableViewDataSource, UITableViewDelegate>
- (nonnull instancetype)initWithVideoPath:(NSString * _Nonnull)videoPath OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC20ZiggeoSwiftFramework22CoverSelectorTableCell")
@interface CoverSelectorTableCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC20ZiggeoSwiftFramework20RecordedVideoPreview")
@interface RecordedVideoPreview : UIViewController
@property (nonatomic, copy) NSURL * _Null_unspecified videoURL;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) BOOL shouldAutorotate;
- (void)killPlayer;
- (void)viewDidAppear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

@class ZiggeoConfig;
@class ZiggeoConnect;
@class ZiggeoVideos;

SWIFT_CLASS("_TtC20ZiggeoSwiftFramework6Ziggeo")
@interface Ziggeo : NSObject
- (nonnull instancetype)initWithToken:(NSString * _Nonnull)token OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull token;
@property (nonatomic, readonly, strong) ZiggeoConfig * _Nonnull config;
@property (nonatomic, strong) ZiggeoConnect * _Null_unspecified connect;
@property (nonatomic, strong) ZiggeoVideos * _Null_unspecified videos;
@property (nonatomic) BOOL enableDebugLogs;
- (void)logWithItem:(NSString * _Nonnull)item;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC20ZiggeoSwiftFramework12ZiggeoConfig")
@interface ZiggeoConfig : NSObject
@property (nonatomic, copy) NSString * _Nonnull serverAPIUrl;
@property (nonatomic, copy) NSString * _Nonnull cdnAPIUrl;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSURLSession;
@class NSURLSessionDataTask;
@class NSURLSessionTask;
@class NSDictionary;
@class NSURLResponse;
@class NSError;
@class NSArray;

SWIFT_CLASS("_TtC20ZiggeoSwiftFramework13ZiggeoConnect")
@interface ZiggeoConnect : NSObject <NSURLSessionDataDelegate, NSURLSessionDelegate, NSURLSessionTaskDelegate>
- (void)URLSession:(NSURLSession * _Nonnull)session dataTask:(NSURLSessionDataTask * _Nonnull)dataTask didReceiveData:(NSData * _Nonnull)data;
- (void)URLSession:(NSURLSession * _Nonnull)session task:(NSURLSessionTask * _Nonnull)task didCompleteWithError:(NSError * _Nullable)error;
- (void)URLSession:(NSURLSession * _Nonnull)session task:(NSURLSessionTask * _Nonnull)task didSendBodyData:(int64_t)bytesSent totalBytesSent:(int64_t)totalBytesSent totalBytesExpectedToSend:(int64_t)totalBytesExpectedToSend;
- (void)appWakeupSignalTaskComplete:(NSString * _Nonnull)sessionID;
- (NSString * _Nonnull)formatURLRequest:(NSURLRequest * _Nonnull)request;
- (NSURLSessionTask * _Nonnull)backgroundUploadWithPath:(NSString * _Nonnull)path data:(NSDictionary * _Nullable)data identifier:(NSString * _Nonnull)identifier file:(NSString * _Nonnull)file callback:(void (^ _Nullable)(NSData * _Nullable, NSURLResponse * _Nullable, NSError * _Nullable))callback progress:(void (^ _Nullable)(int64_t, int64_t))progress;
- (NSURLSessionTask * _Nonnull)postRawDataWithPath:(NSString * _Nonnull)path data:(NSData * _Nonnull)data callback:(void (^ _Nonnull)(NSData * _Nullable, NSURLResponse * _Nullable, NSError * _Nullable))callback;
- (NSURLSessionTask * _Nonnull)requestWithMethod:(NSString * _Nonnull)method path:(NSString * _Nonnull)path data:(NSDictionary * _Nullable)data callback:(void (^ _Nonnull)(NSData * _Nullable, NSURLResponse * _Nullable, NSError * _Nullable))callback;
- (NSURLSessionTask * _Nonnull)requestStringWithMethod:(NSString * _Nonnull)method path:(NSString * _Nonnull)path data:(NSDictionary * _Nullable)data callback:(void (^ _Nonnull)(NSString * _Nullable, NSURLResponse * _Nullable, NSError * _Nullable))callback;
- (NSURLSessionTask * _Nonnull)requestJSONWithMethod:(NSString * _Nonnull)method path:(NSString * _Nonnull)path data:(NSDictionary * _Nullable)data callback:(void (^ _Nonnull)(NSDictionary * _Nullable, NSURLResponse * _Nullable, NSError * _Nullable))callback;
- (NSURLSessionTask * _Nonnull)requestJSONArrayWithMethod:(NSString * _Nonnull)method path:(NSString * _Nonnull)path data:(NSDictionary * _Nullable)data callback:(void (^ _Nonnull)(NSArray * _Nullable, NSURLResponse * _Nullable, NSError * _Nullable))callback;
- (NSURLSessionTask * _Nonnull)getWithPath:(NSString * _Nonnull)path data:(NSDictionary * _Nullable)data callback:(void (^ _Nonnull)(NSData * _Nullable, NSURLResponse * _Nullable, NSError * _Nullable))callback;
- (NSURLSessionTask * _Nonnull)getStringWithPath:(NSString * _Nonnull)path data:(NSDictionary * _Nullable)data callback:(void (^ _Nonnull)(NSString * _Nullable, NSURLResponse * _Nullable, NSError * _Nullable))callback;
- (NSURLSessionTask * _Nonnull)getJsonWithPath:(NSString * _Nonnull)path data:(NSDictionary * _Nullable)data callback:(void (^ _Nonnull)(NSDictionary * _Nullable, NSURLResponse * _Nullable, NSError * _Nullable))callback;
- (NSURLSessionTask * _Nonnull)getJsonArrayWithPath:(NSString * _Nonnull)path data:(NSDictionary * _Nullable)data callback:(void (^ _Nonnull)(NSArray * _Nullable, NSURLResponse * _Nullable, NSError * _Nullable))callback;
- (NSURLSessionTask * _Nonnull)postWithPath:(NSString * _Nonnull)path data:(NSDictionary * _Nullable)data callback:(void (^ _Nonnull)(NSData * _Nullable, NSURLResponse * _Nullable, NSError * _Nullable))callback;
- (NSURLSessionTask * _Nonnull)postJsonWithPath:(NSString * _Nonnull)path data:(NSDictionary * _Nullable)data callback:(void (^ _Nonnull)(NSDictionary * _Nullable, NSURLResponse * _Nullable, NSError * _Nullable))callback;
- (NSURLSessionTask * _Nonnull)deleteWithPath:(NSString * _Nonnull)path data:(NSDictionary * _Nullable)data callback:(void (^ _Nonnull)(NSData * _Nullable, NSURLResponse * _Nullable, NSError * _Nullable))callback;
- (NSURLSessionTask * _Nonnull)deleteJsonWithPath:(NSString * _Nonnull)path data:(NSDictionary * _Nullable)data callback:(void (^ _Nonnull)(NSDictionary * _Nullable, NSURLResponse * _Nullable, NSError * _Nullable))callback;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@class AVPlayerItem;

SWIFT_CLASS("_TtC20ZiggeoSwiftFramework12ZiggeoPlayer")
@interface ZiggeoPlayer : AVPlayer
- (nonnull instancetype)initWithApplication:(Ziggeo * _Nonnull)application videoToken:(NSString * _Nonnull)videoToken OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithURL:(NSURL * _Nonnull)URL SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithPlayerItem:(AVPlayerItem * _Nullable)item SWIFT_UNAVAILABLE;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@class UIImage;
@protocol UIViewControllerTransitionCoordinator;
@class AVCaptureFileOutput;

SWIFT_CLASS("_TtC20ZiggeoSwiftFramework14ZiggeoRecorder")
@interface ZiggeoRecorder : UIViewController <AVCaptureFileOutputRecordingDelegate>
@property (nonatomic) BOOL coverSelectorEnabled;
@property (nonatomic) BOOL cameraFlipButtonVisible;
@property (nonatomic) UIImagePickerControllerCameraDevice cameraDevice;
- (nonnull instancetype)initWithApplication:(Ziggeo * _Nonnull)application;
- (nonnull instancetype)initWithApplication:(Ziggeo * _Nonnull)application videoToken:(NSString * _Null_unspecified)videoToken OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)retake:(NSURL * _Null_unspecified)fileToBeRemoved;
- (void)upload:(NSURL * _Nonnull)fileToUpload;
- (void)coverSelected:(NSString * _Nonnull)videoPath image:(UIImage * _Null_unspecified)image;
@property (nonatomic, readonly) BOOL shouldAutorotate;
@property (nonatomic, readonly) UIInterfaceOrientationMask supportedInterfaceOrientations;
- (void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id <UIViewControllerTransitionCoordinator> _Nonnull)coordinator;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (void)observeValueForKeyPath:(NSString * _Nullable)keyPath ofObject:(id _Nullable)object change:(NSDictionary<NSKeyValueChangeKey, id> * _Nullable)change context:(void * _Nullable)context;
- (void)captureOutput:(AVCaptureFileOutput * _Null_unspecified)captureOutput didStartRecordingToOutputFileAtURL:(NSURL * _Null_unspecified)fileURL fromConnections:(NSArray * _Null_unspecified)connections;
- (void)captureOutput:(AVCaptureFileOutput * _Null_unspecified)captureOutput didFinishRecordingToOutputFileAtURL:(NSURL * _Null_unspecified)outputFileURL fromConnections:(NSArray * _Null_unspecified)connections error:(NSError * _Null_unspecified)error;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC20ZiggeoSwiftFramework12ZiggeoVideos")
@interface ZiggeoVideos : NSObject
- (NSURLSessionTask * _Nonnull)index:(NSDictionary * _Nullable)data callback:(void (^ _Nonnull)(NSArray * _Nullable, NSError * _Nullable))callback;
- (NSURLSessionTask * _Nonnull)attachVideo:(NSString * _Nonnull)token streamToken:(NSString * _Nonnull)streamToken data:(NSDictionary * _Nullable)data file:(NSString * _Nonnull)file callback:(void (^ _Nullable)(NSDictionary * _Nullable, NSURLResponse * _Nullable, NSError * _Nullable))callback progress:(void (^ _Nullable)(int64_t, int64_t))progress;
- (NSURLSessionTask * _Nonnull)createVideo:(NSDictionary * _Nullable)data file:(NSString * _Nonnull)file cover:(UIImage * _Nullable)cover callback:(void (^ _Nullable)(NSDictionary * _Nullable, NSURLResponse * _Nullable, NSError * _Nullable))callback progress:(void (^ _Nullable)(int64_t, int64_t))progress;
- (NSURLSessionTask * _Nonnull)reRecordVideo:(NSString * _Nonnull)token file:(NSString * _Nonnull)file callback:(void (^ _Nullable)(NSDictionary * _Nullable, NSURLResponse * _Nullable, NSError * _Nullable))callback progress:(void (^ _Nullable)(int64_t, int64_t))progress;
- (NSURLSessionTask * _Nullable)getImageForVideo:(NSString * _Nonnull)token callback:(void (^ _Nonnull)(UIImage * _Nullable, NSURLResponse * _Nullable, NSError * _Nullable))callback;
- (void)getImageForLocalVideo:(NSString * _Nonnull)path callback:(void (^ _Nonnull)(UIImage * _Nullable, NSError * _Nullable))callback;
- (NSString * _Nonnull)getURLForVideo:(NSString * _Nonnull)token;
- (NSURLSessionTask * _Nonnull)deleteVideo:(NSString * _Nonnull)token callback:(void (^ _Nullable)(NSData * _Nullable, NSURLResponse * _Nullable, NSError * _Nullable))callback;
- (NSURLSessionTask * _Nonnull)getDefaultStream:(NSString * _Nonnull)token callback:(void (^ _Nullable)(NSString * _Nullable, NSURLResponse * _Nullable, NSError * _Nullable))callback;
- (NSURLSessionTask * _Nonnull)createStream:(NSString * _Nonnull)token callback:(void (^ _Nonnull)(NSDictionary * _Nullable, NSURLResponse * _Nullable, NSError * _Nullable))callback;
- (NSURLSessionTask * _Nonnull)createEmptyVideo:(NSDictionary * _Nullable)data callback:(void (^ _Nonnull)(NSDictionary * _Nullable, NSURLResponse * _Nullable, NSError * _Nullable))callback;
- (NSURLSessionTask * _Nonnull)recorderSubmit:(NSString * _Nonnull)token streamToken:(NSString * _Nonnull)streamToken callback:(void (^ _Nonnull)(NSDictionary * _Nullable, NSURLResponse * _Nullable, NSError * _Nullable))callback;
- (void)enforceImageForVideo:(NSString * _Nonnull)path image:(UIImage * _Nonnull)image;
- (NSURLSessionTask * _Nullable)attachCover:(NSString * _Nonnull)token streamToken:(NSString * _Nonnull)streamToken cover:(UIImage * _Nullable)cover callback:(void (^ _Nullable)(NSData * _Nullable, NSURLResponse * _Nullable, NSError * _Nullable))callback;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

#pragma clang diagnostic pop
