platform :ios, '11.0'

use_frameworks!

target 'ZiggeoDemoSwift' do

#  pod 'ZiggeoSwiftSDK', :path => '../../'
  pod 'ZiggeoSwiftSDK', :git => 'https://github.com/Ziggeo/Swift-Client-SDK.git', :branch => 'blurring'
  pod 'ActiveLabel'
  pod 'SideMenu'
  pod 'SVProgressHUD'
  pod 'PINRemoteImage'
  pod 'IQKeyboardManagerSwift'

end
