platform :ios, '11.0'

use_frameworks!

target 'ZiggeoDemoSwift' do
  
  target 'BroadcastExtension' do
    inherit! :search_paths
  end

  pod 'ZiggeoMediaSwiftSDK', :git => 'https://github.com/Ziggeo/Swift-Client-SDK.git'

  pod 'ActiveLabel'
  pod 'SideMenu'
  pod 'SVProgressHUD'
  pod 'PINRemoteImage'
  pod 'IQKeyboardManagerSwift'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
        config.build_settings['BITCODE_GENERATION_MODE'] = 'bitcode'
        config.build_settings['ENABLE_BITCODE'] = 'YES'
      end
    end
  end
  
end
